[package]
name = "mini-db"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "mini-db"
path = "src/bin/main.rs"

[[bin]]
name = "mini-client"
path = "src/bin/client.rs"

[[bench]]
name = "bench"
path = "bench/bench.rs"
harness = false
test = false
doctest = false

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
clap = { version = "4.6.6", features = ["derive"] }
memmap2 = "0.9.11"
bytes = "1.12.1"
anyhow = "1.0.104"
chrono = "0.4.45"
colored = "3.1.1"
crc32fast = "1.5.1"
rand = "0.10.2"