[package]
name = "mini-db"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mini-db"
path = "src/bin/main.rs"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
clap = { version = "4.6.6", features = ["derive"] }
anyhow = "1.0.104"
bytes = "1.12.1"
chrono = "0.4.45"
colored = "3.1.1"
crc32fast = "1.5.1"
# memmap2 = "0.9.11"
